<Project Sdk="Dalamud.NET.Sdk/12.0.2">

    <PropertyGroup>
        <Authors>Haplo064, Lother</Authors>
        <Version>7.15.0.1</Version>
        <Description>Perfecting Pixels</Description>
        <PackageProjectUrl>https://github.com/Haplo064/PixelPerfect</PackageProjectUrl>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

</Project>
